=== DeepseaPlatform/coastal/docs/coastal.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT configuration (coastal,green?)>
<!ELEMENT coastal (jar|main|target|trigger|strategy|randomseed|delegate|observer|trace-all|echo-output|draw-paths|concrete-values|limits)*>
<!ELEMENT jar (#PCDATA)>
<!ATTLIST jar direction CDATA #IMPLIED>
<!ELEMENT main (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT trigger (#PCDATA)>
<!ELEMENT strategy (#PCDATA)>
<!ELEMENT randomseed (#PCDATA)>
<!ELEMENT delegate (target,model)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT observer (#PCDATA)>
<!ELEMENT trace-all (#PCDATA)>
<!ELEMENT echo-output (#PCDATA)>
<!ELEMENT draw-paths (#PCDATA)>
<!ELEMENT concrete-values (#PCDATA)>
<!ELEMENT limits (runs|time|path|conjuncts)*>
<!ELEMENT runs (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT conjuncts (#PCDATA)>
<!ELEMENT green (z3)>
<!ELEMENT z3 (path)>

=== DeepseaPlatform/coastal/src/test/java/tests/strings/CharAt01.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration PUBLIC "-//DEEPSEA//COASTAL configuration//EN" "https://deepseaplatform.github.io/coastal/coastal.dtd">
<configuration>
	<coastal>
		<main>tests.strings.CharAt01</main>
		<target>tests.strings</target>
		<trigger>tests.strings.CharAt01.test(S: String, X: int)</trigger>
		<delegate>
			<target>java.lang.String</target>
			<model>za.ac.sun.cs.coastal.model.String</model>
		</delegate>
		<strategy threads="1">za.ac.sun.cs.coastal.strategy.pathbased.DepthFirstFactory</strategy>
		<diver threads="1"/>
		<trace-all>false</trace-all>
		<echo-output>false</echo-output>
		<draw-paths>false</draw-paths>
		<concrete-values>true</concrete-values>
		<limits>
			<runs>0</runs>
			<time>0</time>
			<path>0</path>
			<conjuncts>0</conjuncts>
		</limits>
	</coastal>
</configuration>

=== DeepseaPlatform/coastal/src/test/java/tests/arrays/Array01.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration PUBLIC "-//DEEPSEA//COASTAL configuration//EN" "https://deepseaplatform.github.io/coastal/coastal.dtd">
<configuration>
	<coastal>
		<main>tests.arrays.Array01</main>
		<target>tests.arrays</target>
		<trigger>tests.arrays.Array01.test(X: int, Y: int)</trigger>
		<bound name="X" min="-1000" max="1000"/>
		<bound name="Y" min="-1000" max="1000"/>
		<strategy>za.ac.sun.cs.coastal.strategy.pathbased.DepthFirstFactory</strategy>
		<trace-all>false</trace-all>
		<echo-output>false</echo-output>
		<draw-paths>false</draw-paths>
		<concrete-values>true</concrete-values>
		<limits>
			<runs>0</runs>
			<time>0</time>
			<path>0</path>
			<conjuncts>0</conjuncts>
		</limits>
	</coastal>
</configuration>

=== DeepseaPlatform/coastal/src/test/java/tests/arrays/Sorting02.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration PUBLIC "-//DEEPSEA//COASTAL configuration//EN" "https://deepseaplatform.github.io/coastal/coastal.dtd">
<configuration>
	<coastal>
		<main>tests.arrays.Sorting02</main>
		<target>tests.arrays</target>
		<trigger>tests.arrays.Sorting02.sort(A: int[])</trigger>
		<strategy>za.ac.sun.cs.coastal.strategy.pathbased.DepthFirstFactory</strategy>
		<trace-all>false</trace-all>
		<echo-output>false</echo-output>
		<draw-paths>false</draw-paths>
		<concrete-values>true</concrete-values>
		<limits>
			<runs>0</runs>
			<time>0</time>
			<path>0</path>
			<conjuncts>0</conjuncts>
		</limits>
	</coastal>
</configuration>

=== DeepseaPlatform/coastal/src/main/java/examples/strings/CharAt.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration PUBLIC "-//DEEPSEA//COASTAL configuration//EN" "https://deepseaplatform.github.io/coastal/coastal.dtd">
<configuration>
	<coastal>
		<main>examples.strings.CharAt</main>
		<target>examples.strings</target>
		<trigger>examples.strings.CharAt.test(S: String, X: int)</trigger>
		<delegate>
			<target>java.lang.String</target>
			<model>za.ac.sun.cs.coastal.model.String</model>
		</delegate>
	</coastal>
</configuration>

=== DeepseaPlatform/coastal/src/main/java/examples/strings/Mystery.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration PUBLIC "-//DEEPSEA//COASTAL configuration//EN" "https://deepseaplatform.github.io/coastal/coastal.dtd">
<configuration>
	<coastal>
		<main>examples.strings.Mystery</main>
		<target>examples.strings</target>
		<trigger>examples.strings.Mystery.preserveSomeHtmlTagsAndRemoveWhitespaces(S: String)</trigger>
		<delegate>
			<target>java.lang.String</target>
			<model>za.ac.sun.cs.coastal.model.String</model>
		</delegate>
		<observer>za.ac.sun.cs.coastal.observers.StopControllerFactory</observer>
		<draw-paths>true</draw-paths>
		<concrete-values>false</concrete-values>
	</coastal>
</configuration>

=== DeepseaPlatform/coastal/src/test/java/tests/jars/jpf-regression.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration PUBLIC "-//DEEPSEA//COASTAL configuration//EN" "https://deepseaplatform.github.io/coastal/coastal.dtd">
<configuration>
	<coastal>
		<main>Main</main>
		<target>Main</target>
		<trigger>Main.main(String)</trigger>
		<strategy>za.ac.sun.cs.coastal.strategy.pathbased.DepthFirstFactory</strategy>
		<observer>za.ac.sun.cs.coastal.observers.AssertControllerFactory</observer>
		<trace-all>false</trace-all>
		<echo-output>true</echo-output>
		<draw-paths>false</draw-paths>
		<concrete-values>true</concrete-values>
		<limits>
			<runs>0</runs>
			<time>0</time>
			<path>0</path>
			<conjuncts>0</conjuncts>
		</limits>
	</coastal>
</configuration>

=== DeepseaPlatform/coastal/src/main/java/examples/statik/Statik03A.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration PUBLIC "-//DEEPSEA//COASTAL configuration//EN" "https://deepseaplatform.github.io/coastal/coastal.dtd">
<configuration>
	<coastal>
		<main>examples.statik.Statik03A</main>
		<target>examples.statik.Statik03A</target>
		<trigger>examples.statik.Statik03A.run(X: int)</trigger>
		<bound name="X" max="10" min="0"/>
		<trace-all>true</trace-all>
		<draw-paths>true</draw-paths>
		<echo-output>true</echo-output>
	</coastal>
</configuration>

=== DeepseaPlatform/coastal/src/test/java/tests/observers/MarkerCoverage01.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration PUBLIC "-//DEEPSEA//COASTAL configuration//EN" "https://deepseaplatform.github.io/coastal/coastal.dtd">
<configuration>
	<coastal>
		<main>tests.observers.MarkerCoverage01</main>
		<target>tests.observers</target>
		<trigger>tests.observers.MarkerCoverage01.compute(X: int, Y: int, Z: int)</trigger>
		<bound name="X" min="-1000" max="1000"/>
		<bound name="Y" min="-1000" max="1000"/>
		<bound name="Z" min="-1000" max="1000"/>
		<observer>za.ac.sun.cs.coastal.observers.MarkerCoverageFactory</observer>
		<strategy>za.ac.sun.cs.coastal.strategy.pathbased.DepthFirstFactory</strategy>
		<trace-all>false</trace-all>
		<echo-output>false</echo-output>
		<draw-paths>false</draw-paths>
		<concrete-values>true</concrete-values>
		<limits>
			<runs>0</runs>
			<time>0</time>
			<path>0</path>
			<conjuncts>0</conjuncts>
		</limits>
	</coastal>
</configuration>
